// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/:lang?": {
    params: {
      "lang"?: string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/:lang?" | "/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/:lang?";
  };
  "routes/catch-all.tsx": {
    id: "routes/catch-all";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/catch-all": typeof import("./app/routes/catch-all.tsx");
};